AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'bin/*'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 15

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'bin/alttext-mcp'

Style/Documentation:
  Enabled: false
